# Generated by Django 5.2.15 on 2026-06-13 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'industries',
                'db_table': 'industries',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_abr', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('job_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField()),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('med_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_period', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('views', models.IntegerField(blank=True, null=True)),
                ('applies', models.IntegerField(blank=True, null=True)),
                ('original_listed_time', models.BigIntegerField(blank=True, null=True)),
                ('listed_time', models.BigIntegerField(blank=True, null=True)),
                ('expiry', models.BigIntegerField(blank=True, null=True)),
                ('closed_time', models.BigIntegerField(blank=True, null=True)),
                ('remote_allowed', models.BooleanField(blank=True, db_index=True, null=True)),
                ('job_posting_url', models.URLField(blank=True, max_length=500, null=True)),
                ('application_url', models.URLField(blank=True, max_length=500, null=True)),
                ('application_type', models.CharField(blank=True, max_length=100, null=True)),
                ('formatted_work_type', models.CharField(blank=True, max_length=100, null=True)),
                ('work_type', models.CharField(blank=True, max_length=50, null=True)),
                ('formatted_experience_level', models.CharField(blank=True, max_length=100, null=True)),
                ('skills_desc', models.TextField(blank=True, null=True)),
                ('posting_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('sponsored', models.BooleanField(default=False)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('compensation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('normalized_salary', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=12, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('fips', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_postings', to='company.company')),
                ('industries', models.ManyToManyField(db_table='job_industries', related_name='job_postings', to='jobs.industry')),
                ('skills', models.ManyToManyField(db_table='job_skills', related_name='job_postings', to='jobs.skill')),
            ],
            options={
                'db_table': 'postings',
            },
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inferred', models.BooleanField(default=False)),
                ('type', models.CharField(max_length=255)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='jobs.jobposting')),
            ],
            options={
                'db_table': 'benefits',
            },
        ),
        migrations.CreateModel(
            name='JobSalaryDetail',
            fields=[
                ('salary_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('med_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pay_period', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('compensation_type', models.CharField(blank=True, max_length=50, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_details', to='jobs.jobposting')),
            ],
            options={
                'db_table': 'salaries',
            },
        ),
    ]
