# Generated by Django 5.2.15 on 2026-06-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_company_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='data_source',
            field=models.CharField(choices=[('CSV', 'CSV'), ('API', 'API')], db_index=True, default='CSV', max_length=10),
        ),
    ]
